// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcU0DTpz9l0eCJAODW2KAWF4ILwrxi_cM',
    appId: '1:1050972285937:web:508268b1f2023bfe90f250',
    messagingSenderId: '1050972285937',
    projectId: 'flutterauth-67fdc',
    authDomain: 'flutterauth-67fdc.firebaseapp.com',
    storageBucket: 'flutterauth-67fdc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHviGtdS3EDDsg1S8MdkO9JGyAp8kWK74',
    appId: '1:1050972285937:android:827c801a5349f99990f250',
    messagingSenderId: '1050972285937',
    projectId: 'flutterauth-67fdc',
    storageBucket: 'flutterauth-67fdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIYBWJMQb8rraXbLjaGwl9rxYxL1VsyJ0',
    appId: '1:1050972285937:ios:3ba7c8b21a140d7f90f250',
    messagingSenderId: '1050972285937',
    projectId: 'flutterauth-67fdc',
    storageBucket: 'flutterauth-67fdc.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIYBWJMQb8rraXbLjaGwl9rxYxL1VsyJ0',
    appId: '1:1050972285937:ios:faa5e1533aedbae690f250',
    messagingSenderId: '1050972285937',
    projectId: 'flutterauth-67fdc',
    storageBucket: 'flutterauth-67fdc.appspot.com',
    iosBundleId: 'com.example.loginAuth.RunnerTests',
  );
}
